### ISSUE TITLE
Image tag validation pattern is too restrictive

### ISSUE THREAD

**Issue by edclement** [b3outputs/helm-charts#5]
Hi, first thanks for maintaining this chart as it is very useful for basic service/app deployments. I've run into one issue though. The image tag validation pattern is very restrictive:
```json
"tag": {
  "type": "string",
  "pattern": "^[a-z0-9-_]+$"
}
```

The regex pattern prevents version numbers (e.g. `1.2.3`) and other standard tag name conventions. Looking at the official [node image](https://hub.docker.com/_/node), most of those tags won't work. Can the tag regex be loosened up a little? I can open a PR if you prefer.

I was thinking something like:
```
^[\w.-]+$
```
...which would allow tags like `17.0.1-stretch-slim` to work properly.

**Comment by bgcorreia** [comment]
Hi @edclement, thanks for support. About the chart, you have reason this pattern is very restrictive. I've proved your change in #7 and it's perfect.
