### ISSUE TITLE
Probe ports use wrong `Values` reference

### ISSUE THREAD

**Issue by edclement** [b3outputs/helm-charts#6]
I just ran into an issue where all of the `deployment` probes have the `port` templated as:
```
port: {{ $dot.Values.containerPort }}
```

These should actually be:
```
port: {{ $dot.Values.app.containerPort }}
```

I can open a PR if preferred. Thanks.

**Comment by bgcorreia** [comment]
Thanks @edclement for finding, correcting and doing the PR that fixes the problem!
